### ISSUE TITLE
Fixing user-specified gn and Qn, the result doesn't change from iteration to iteration

### ISSUE THREAD

**Issue by mambastats** [benkeser/drtmle#15]
Hi all, when I'm trying to use drtmle with my own specified initial estimates in gn and Qn, the result doesn't change from iteration to iteration. Am I missing something?
Thanks!

**Comment by benkeser** [comment]
Are you saying that the results don't change when you re-run with the same inputs? I wouldn't expect them to. If gn, Qn are fixed, then, assuming the method for estimating Qr and gr doesn't change across iterations, nothing is random about the procedure, so you'd expect to get the same results.

**Comment by mambastats** [comment]
Thank you for the quick response. Is it possible to estimate the propensity score and outcome regression from procedures outside the options provided in drtmle and use them as initial estimators and iterate from my own inputted estimators with drtmle algorithm?

**Comment by benkeser** [comment]
Yes. See `Qn` and `gn` arguments [here](https://benkeser.github.io/drtmle/reference/drtmle.html#arguments).

**Comment by mambastats** [comment]
Many thanks for the quick response!
