### ISSUE TITLE
drtmle not changing from iteration to iteration if specifying outcome model as zero

### ISSUE THREAD

**Issue by jameszou1206** [benkeser/drtmle#19]
Hi, I run into another issue while using drtmle: when I specify glm_Q = '0' (putting constant zeros as starting outcome model estimates), drtmle doesn't seem to run its iterative algorithm, but glm_Q = '1' still works.

X <- runif(100, 0, 1)

Q <- X

g <- exp(X) / (1 + exp(X))

A <- rbinom(100, 1, g)

Y <- Q + runif(100, -0.1, 0.1)

X <- as.data.frame(X)

## Zero to Q

a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 1)
## [1] -0.03679124

a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 2)
## Intercept only model

a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '1', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 1)
## [1] 0.4682421

a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '1', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 2)

**Comment by benkeser** [comment]
It's likely that the algorithm simply converged after a single iteration in the first case, but not in the second. You can confirm by checking that that each component of `a$ic_drtmle$eif` is smaller than `tolIC` in this run:
```r
a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 1)
```
but not in this one
```r
a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '1', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 1)
```

In general, the code will iterate until it hits `maxIter` or until the empirical mean of each component of the estimated influence function is less than `tolIC`, whichever comes first. 

From the documentation: 
`ic_drtmle`
* A list of the empirical mean of the efficient influence function ($eif) and the extra pieces of the influence function resulting from misspecification. All should be smaller than tolIC (unless maxIter was reached first). Also includes a matrix of the influence function values at the estimated nuisance parameters evaluated at the observed data.

**Comment by benkeser** [comment]
Closing issue, but will reopen if you find that the `tolIC` is not behaving as expected.

**Comment by jameszou1206** [comment]
Thanks! Actually I just checked that the following: the mean_eif changes very slightly iteration after iteration but the estimator doesn't at all. Also, the mean_eif is way larger than tolIC I specified. In addition, when I set iteration = 20 it does take longer time to run than 1 or 5 iterations so it doesn't stop early. Am I missing something?

1 Iteration
```
> a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 1, tolIC = 1e-13)
> a$drtmle$est
[1] -0.03679124
> a$ic_drtmle$mean_eif
[1] 0.5048372
```

5 Iterations:
```
> a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 5, tolIC = 1e-13)
> a$drtmle$est
[1] -0.03679124
> a$ic_drtmle$mean_eif
$`1`
[1] 0.504241
```
20 Iterations:
```
> a <- drtmle(W = X, A = A, Y = Y, a_0 = 1, glm_Q = '0', glm_g = 'X', SL_Qr = 'SL.npreg', guard = 'Q', returnModel = TRUE, maxIter = 20, tolIC = 1e-13)
> a$drtmle$est
[1] -0.03679124
> a$ic_drtmle$mean_eif
$`1`
[1] 0.5042409
```

**Comment by benkeser** [comment]
The issue appears to be because these initial estimates result in a submodel whose log-likelihood is very flat, so the iteratively re-weighted least squares implemented in `glm` has trouble converging to a sane MLE. 

I don't know whether it's worth my pursuing this further. I could throw a warning for when this happens. However, this example is pretty contrived (e.g., if you use `glm_Q = 'X'` in your call, you'll recover sane answers), so I'm hesitant to introduce unnecessary warnings.
