### ISSUE TITLE
transparent future: please use sequential instead (transparent is not meant for production)

### ISSUE THREAD

**Issue by HenrikBengtsson** [benkeser/drtmle#22]
Hi.  As part of taking the **future** package to the next level, I'm narrowing down what futures may do.  This is mostly backward compatible, but one thing that needs to go is the support for `future(..., local = FALSE)`.  Most of this has already been done, cf. https://github.com/HenrikBengtsson/future/issues/382.  However, it is still used internally by `transparent` futures, which I'll keep supporting for a while, but they should only be used for debugging and troubleshooting purposes. They should never for production use  The reason for this is that `local = FALSE` introduces behavior that is an outlier in the future framework.   (This will be clarified further in the next release of **future**).

Running reverse dependency checks, I spotted that **drtmle** uses `transparent` futures in two places:

https://github.com/benkeser/drtmle/blob/922844d0e35a7f514965f3de3ba645627c507bca/R/adaptive_iptw.R#L148

https://github.com/benkeser/drtmle/blob/922844d0e35a7f514965f3de3ba645627c507bca/R/drtmle.R#L243

Could you please switch to use `sequential` here instead?

BTW, I have a vague memory that you've asked about how to run futures with near-zero overhead.  Is this why you used `transparent` here rather than `sequential`?  If so, I'm not sure how much difference that makes these days relative to the other types of overhead that exist, e.g. relaying of stdout and conditions.

**Comment by benkeser** [comment]
Resolved in v1.1.0
