### ISSUE TITLE
future::plan(): always undo changes 

### ISSUE THREAD

**Issue by HenrikBengtsson** [benkeser/drtmle#23]
Please undo the changes to `future::plan()` you do when you exit your function in for instance,

https://github.com/benkeser/drtmle/blob/922844d0e35a7f514965f3de3ba645627c507bca/R/adaptive_iptw.R#L147-L168

From ?future::plan:

> # For package developers
> 
> Please refrain from modifying the future strategy inside your packages / functions, i.e. do not call `plan()` in your code. Instead, leave the control on what backend to use to the end user. This idea is part of the core philosophy of the future framework - as a developer you can never know what future backends the user have access to. Moreover, by not making any assumptions about what backends are available, your code will also work automatically with any new backends developed after you wrote your code.
> 
> If you think it is necessary to modify the future strategy within a function, then make sure to undo the changes when exiting the function. This can be done using:
> 
> ```r
>   oplan <- plan(new_set_of_strategies)
>   on.exit(plan(oplan), add = TRUE)
>   [...]
> ```
> 
> This is important because the end-user might have already set the future strategy elsewhere for other purposes and will most likely not known that calling your function will break their setup. Remember, your package and its functions might be used in a greater context where multiple packages and functions are involved and those might also rely on the future framework, so it is important to avoid stepping on others' toes. 

BTW,

1.  The `&` in `all(c("sequential", "uniprocess") %in% class(future::plan())) & is.null(future_hpc)` could be replaced with a `&&` to make that statement more robust.
2. I think `inherits(future::plan(), c("sequential", "uniprocess"))` is better than `c("sequential", "uniprocess") %in% class(future::plan())`.

**Comment by benkeser** [comment]
Resolved in v1.1.0
