### ISSUE TITLE
Issue with delta method and 'contrast'

### ISSUE THREAD

**Issue by jeffbone** [benkeser/drtmle#24]
Hi,

I'm noticing an issue with the risk ratio 'contrast' option in ci() in cases with a multi-level treatment. Here is the example from the vignette where I've computed the risk ratio and confidence interval 3 ways (two manually, which agree, and one with ci(), which is much wider): 

```r
library(drtmle)
library(dplyr)
library(SuperLearner)


#simulate data as in vignette
set.seed(1234)
n <- 200
W <- data.frame(W1 = runif(n), W2 = rbinom(n, 1, 0.5))
A <- rbinom(n, 2, plogis(W$W1 + W$W2))
Y <- rbinom(n, 1, plogis(W$W1 + W$W2*A))

glm_fit_multiA <- drtmle(W = W, A = A, Y = Y, stratify = FALSE,
                                      glm_g = "W1 + W2", glm_Q = "W1 + W2*A",
                                      glm_gr = "Qn", glm_Qr = "gn",
                                      family = binomial(), a_0 = c(0,1,2))
##

#compute RR as per example
riskRatio <- list(f = function(eff){ log(eff) },
                  f_inv = function(eff){ exp(eff) },
                  h = function(est){ est[1]/est[2] },
                  fh_grad =  function(est){ c(1/est[1],-1/est[2], 0) }) #added 0
CI.builtin <- ci(glm_fit_multiA, contrast = riskRatio)

#try manually two ways: 

#1 with gradient manually 
#get TMLE estimates 
psi.0 <- glm_fit_multiA$drtmle$est[1]
psi.1 <- glm_fit_multiA$drtmle$est[2]

#compute gradient 
grad <- (c(1/psi.0,-1/psi.1, 0))%*%glm_fit_multiA$drtmle$cov%*%c(1/psi.0,-1/psi.1, 0)

#CI
CI.grad <- 
  c(log(psi.0/psi.1), 
  log(psi.0/psi.1) - 1.96*sqrt(grad),
  log(psi.0/psi.1) + 1.96*sqrt(grad)) %>% exp()


#2 with influence curve 

#get influence 
d.0 <- glm_fit_multiA$ic_drtmle$ic[,1]
d.1 <- glm_fit_multiA$ic_drtmle$ic[,2]

logRR <- log(psi.0/psi.1) #log risk ratio
eic.log.rr <- d.0/psi.0 - d.1/psi.1 #functional delta method for EIC

var.log.rr <- var(eic.log.rr)/n #variance from EIC

#output on RR scale
CI.ic <- 
  c(logRR,
  (logRR - 1.96*sqrt(var.log.rr)),
  (logRR + 1.96*sqrt(var.log.rr))) %>% exp()


CI.ic #ageees with CI.grad
CI.grad
CI.builtin 



```

**Comment by benkeser** [comment]
Thanks will take a look.

**Comment by jeffbone** [comment]
Thank you, much appreciated for quick response! In case it is useful: 

- I didn't notice this issue with binary treatment using a toy example, or in applied analyses 

- In my applied example (can't post data here unfortunately) the confidence intervals from drtmle::ci() were much wider than what I was getting from a standard regression model, while the CI.grad, and CI.ic I computed were similar in width

**Comment by benkeser** [comment]
A couple things:

* could you try defining `riskRatio` as such:

```r
riskRatio <- list(f = function(eff){ log(eff) },
                  f_inv = function(eff){ exp(eff) },
                  h = function(est){ est[1]/est[2] },
                  fh_grad =  function(est){ c(1/est[1],-1/est[2], 0) }) # note the added 0
```

The `fh_grad` function needs to return a gradient equal to the number of treatments input to `drtmle` (i.e., `length(a_0)`)

* in your example, you reference an object `npreg_fit` that I do not see defined anywhere. When I replace with the `drtmle` object `glm_fit_multiA`, I get an error indicating incorrect dimensions. Maybe a mislabeled model?

**Comment by jeffbone** [comment]
Sorry about the misspecification there - I was testing a couple of different models - revised now above and getting agreement with the 0 added. 

I think that not including the 0 was the issue. I also noticed that the gradient needs to be in the same order as the treatments in ``` a_0```, not in the order of ```h```, which makes sense, but was also causing me an issue I now realize. 

Very much appreciate the quick support, and really enjoying this package for implementation of TMLE.
