### ISSUE TITLE
Fitting with W = 1

### ISSUE THREAD

**Issue by nhejazi** [benkeser/drtmle#4]
In attempting to apply `drtmle` as a replacement for `tmle` I've run into an odd error related to the use of the `predict.lm` method somewhere in `drtmle`. An example that illustrates my problem is given below
```r
n <- 100
W <- rep(1, n)
A <- rbinom(n, 1, 0.5)
Y <- rnorm(n)
y_star <- (Y - min(Y)) / (max(Y) - min(Y))
Q_lib <- g_lib <- c("SL.mean", "SL.glm")

out <- drtmle(Y = as.numeric(y_star),
              A = as.numeric(A),
              W = as.data.frame(W),
              family = family,
              SL_Q = Q_lib,
              SL_g = g_lib,
              SL_Qr = "SL.npreg",
              SL_gr = "SL.npreg"
             )
```

which then results in
```r
Error: $ operator is invalid for atomic vectors
```

use of `traceback` yields
```r
❯ traceback()
7: stop(FutureError(future))
6: value.Future(tmp, ...)
5: value(tmp, ...)
4: values.list(fs)
3: values(fs)
2: future::future_lapply(x = validRows, FUN = estimateQ, Y = Y,
       A = A, W = W, DeltaA = DeltaA, DeltaY = DeltaY, verbose =
verbose,
       returnModels = returnModels, SL_Q = SL_Q, a_0 = a_0, strat
ify = stratify,
       glm_Q = glm_Q, family = family)
1: drtmle(Y = as.numeric(y_test_star), A = as.numeric(A), W = as.
data.frame(W),
       family = family, SL_Q = Q_lib, SL_g = g_lib, SL_Qr = "SL.n
preg",
       SL_gr = "SL.npreg")
```

**Comment by benkeser** [comment]
Probably because there's no variation in W so the GLM is rank deficient. What's the motivation for having W all equal 1?

**Comment by nhejazi** [comment]
Ah, ok, that makes sense. This comes up because I'd like to handle the case where W is actually just an empty set. `tmle` handles with with the W being all 1's but I'm not sure how to hack `drtmle` to get an estimate out.

**Comment by benkeser** [comment]
Off the top of my head I would guess one could either:
- set `glm.Q = "A"` 
- set `glm.Q = "1"` and `stratify = TRUE`
- set `SL.Q = "SL.mean"` and `stratify = TRUE`

**Comment by nhejazi** [comment]
Tried the last of those and it works (I'm sure the others do as well). Thanks for the quick help!
